// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-prospects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-prospects.ts
var list_prospects_default = defineTool({
  name: "list_prospects",
  title: "List prospects",
  description: "List the signed-in user's sales prospects with platform, stage and outcome.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max prospects to return (default 20)."),
    search: z.string().optional().describe("Filter by prospect name (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("prospects").select("id,name,platform,conversation_stage,outcome,conversation_summary,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search?.trim()) query = query.ilike("name", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { prospects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prospect-thread.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_prospect_thread_default = defineTool2({
  name: "get_prospect_thread",
  title: "Get prospect conversation",
  description: "Read the message thread for one prospect, oldest first, including AI suggestions.",
  inputSchema: {
    prospect_id: z2.string().describe("The prospect's id (from list_prospects)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max messages to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ prospect_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: prospect, error: pErr } = await supabase.from("prospects").select("id,name,platform,conversation_stage,outcome,conversation_summary").eq("id", prospect_id).maybeSingle();
    if (pErr) throw new ToolError2(pErr.message);
    if (!prospect) throw new ToolError2("Prospect not found");
    const { data: messages, error } = await supabase.from("chat_messages").select("id,content,direction,is_ai_suggestion,detected_tone,created_at").eq("prospect_id", prospect_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (error) throw new ToolError2(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ prospect, messages: messages ?? [] }, null, 2) }],
      structuredContent: { prospect, messages: messages ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-sales-brain.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_sales_brain_default = defineTool3({
  name: "search_sales_brain",
  title: "Search sales brain",
  description: "Search the user's extracted sales principles (their knowledge brain) by keyword.",
  inputSchema: {
    query: z3.string().describe("Keywords to search principle names, lessons and application notes."),
    limit: z3.number().int().min(1).max(25).optional().describe("Max principles to return (default 8).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const q = query.trim();
    if (!q) throw new ToolError3("query must not be empty");
    const supabase = supabaseForUser(ctx);
    const like = `%${q.replace(/[%,]/g, " ")}%`;
    const { data, error } = await supabase.from("sales_brain").select(
      "id,principle_name,category,what_i_learned,how_to_apply,when_to_use,exact_words_to_use,source_name,power_level"
    ).or(
      `principle_name.ilike.${like},what_i_learned.ilike.${like},how_to_apply.ilike.${like},category.ilike.${like}`
    ).order("power_level", { ascending: false, nullsFirst: false }).limit(limit ?? 8);
    if (error) throw new ToolError3(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { principles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-knowledge-items.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_knowledge_items_default = defineTool4({
  name: "list_knowledge_items",
  title: "List knowledge sources",
  description: "List the user's knowledge base sources (videos, PDFs, links) and their extraction status.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by status, e.g. pending, processing, ready, failed."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max items to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("knowledge_base_items").select("id,title,type,status,url,brain_type,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-prospect-message.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var log_prospect_message_default = defineTool5({
  name: "log_prospect_message",
  title: "Log a prospect message",
  description: "Append a message to a prospect's thread (inbound from the prospect or outbound from the user).",
  inputSchema: {
    prospect_id: z5.string().describe("The prospect's id (from list_prospects)."),
    content: z5.string().describe("Message text to store."),
    direction: z5.enum(["inbound", "outbound"]).describe("inbound = from the prospect, outbound = sent by the user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ prospect_id, content, direction }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const text = content.trim();
    if (!text) throw new ToolError5("content must not be empty");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("chat_messages").insert({ prospect_id, content: text, direction, user_id: ctx.getUserId(), is_ai_suggestion: false }).select("id,content,direction,created_at").maybeSingle();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xbliaagchrfnhhwnnayo";
var mcp_default = defineMcp({
  name: "code-mirror-hub",
  title: "Code Mirror Hub",
  version: "0.1.0",
  instructions: "Tools for the user's AI sales coach workspace. Use `list_prospects` to find prospects, `get_prospect_thread` to read a conversation, `search_sales_brain` to pull the user's own extracted sales principles before advising, `list_knowledge_items` to check knowledge sources and extraction status, and `log_prospect_message` to append a message to a thread. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_prospects_default, get_prospect_thread_default, search_sales_brain_default, list_knowledge_items_default, log_prospect_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
