// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-prospects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-prospects.ts
var list_prospects_default = defineTool({
  name: "list_prospects",
  title: "List prospects",
  description: "List the signed-in user's sales prospects with platform, stage and outcome.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max prospects to return (default 20)."),
    search: z.string().optional().describe("Filter by prospect name (case-insensitive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("prospects").select("id,name,platform,conversation_stage,outcome,conversation_summary,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (search?.trim()) query = query.ilike("name", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { prospects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-prospect-thread.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_prospect_thread_default = defineTool2({
  name: "get_prospect_thread",
  title: "Get prospect conversation",
  description: "Read the message thread for one prospect, oldest first, including AI suggestions.",
  inputSchema: {
    prospect_id: z2.string().describe("The prospect's id (from list_prospects)."),
    limit: z2.number().int().min(1).max(200).optional().describe("Max messages to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ prospect_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data: prospect, error: pErr } = await supabase.from("prospects").select("id,name,platform,conversation_stage,outcome,conversation_summary").eq("id", prospect_id).maybeSingle();
    if (pErr) throw new ToolError2(pErr.message);
    if (!prospect) throw new ToolError2("Prospect not found");
    const { data: messages, error } = await supabase.from("chat_messages").select("id,content,direction,is_ai_suggestion,detected_tone,created_at").eq("prospect_id", prospect_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (error) throw new ToolError2(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify({ prospect, messages: messages ?? [] }, null, 2) }],
      structuredContent: { prospect, messages: messages ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-sales-brain.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
// supabase/functions/_shared/external-brain.ts (inlined)
function sourceKind(type, url) {
  if (type === "pdf") return "pdf";
  if (type === "url" || url) return /youtu\.?be|tiktok\.com|vimeo\.com|instagram\.com\/(?:reel|p)\//i.test(String(url || "")) ? "video" : "web_page";
  return "other";
}
function sourceLink(url, locator) {
  if (!url) return null;
  const start = String(locator || "").match(/^\s*(?:(\d+):)?(\d{1,2}):(\d{2})/);
  if (!start) return url;
  try {
    const link = new URL(url);
    if (!/(^|\.)youtube\.com$|(^|\.)youtu\.be$/i.test(link.hostname)) return url;
    link.searchParams.set("t", `${Number(start[1] || 0) * 3600 + Number(start[2]) * 60 + Number(start[3])}s`);
    return link.toString();
  } catch {
    return url;
  }
}
var search_sales_brain_default = defineTool3({
  name: "search_sales_brain",
  title: "Search sales brain",
  description: "Search the user's Sales Brain: extracted principles AND original passages from their uploaded books, PDFs and video transcripts. Every result names its source (pdf/video/web page), chapter or page/timestamp, and a link (videos open at the exact moment).",
  inputSchema: {
    query: z3.string().describe("What you need, in plain words (any word can match), e.g. 'price objection too expensive'."),
    limit: z3.number().int().min(1).max(25).optional().describe("Max principles and max passages to return (default 8 each)."),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const words = [...new Set(query.toLowerCase().match(/[a-z0-9']{3,}/g) || [])].slice(0, 12);
    if (!words.length) throw new ToolError3("query must contain at least one word");
    const supabase = supabaseForUser(ctx);
    const { data: auth } = await supabase.auth.getUser();
    if (!auth?.user) throw new ToolError3("Not authenticated");
    const max = limit ?? 8;
    // Runs with the caller's permissions (SECURITY INVOKER): only their own vault.
    const { data: rows, error } = await supabase.rpc("search_sales_knowledge", {
      search_query: words.join(" OR "), p_user_id: auth.user.id, match_count: max * 4,
    });
    if (error) throw new ToolError3(error.message);
    const hits = (rows || []);
    const principleRows = hits.filter((hit) => hit.kind === "principle").slice(0, max).map((hit) => hit.record);
    const passageRows = hits.filter((hit) => hit.kind === "passage").slice(0, max).map((hit) => hit.record);
    const sourceIds = [...new Set([...principleRows, ...passageRows].map((row) => row.source_id).filter(Boolean))];
    const { data: sources } = sourceIds.length
      ? await supabase.from("knowledge_base_items").select("id,title,type,url").in("id", sourceIds)
      : { data: [] };
    const sourceById = new Map((sources || []).map((row) => [row.id, row]));
    const describe = (id, fallbackTitle, locator) => {
      const row = id ? sourceById.get(id) : null;
      return { title: row?.title || fallbackTitle || null, type: sourceKind(row?.type, row?.url), url: sourceLink(row?.url, locator) };
    };
    const principles = principleRows.map((p) => ({
      name: p.principle_name,
      source: describe(p.source_id, p.source_name),
      chapter: p.metadata?.chapter ?? null,
      what_it_teaches: p.what_i_learned,
      how_to_apply: p.how_to_apply,
      when_to_use: p.when_to_use,
      exact_words_from_source: p.exact_words_to_use,
      power_level: p.power_level,
    }));
    const passages = passageRows.map((c) => ({
      source: describe(c.source_id, c.metadata?.source_title ?? null, c.locator),
      location: c.locator || null,
      original_text: c.chunk_kind === "source_passage",
      excerpt: String(c.content || "").slice(0, 700),
    }));
    const result = { principles, passages };
    return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }], structuredContent: result };
  },
});

// src/lib/mcp/tools/list-knowledge-items.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_knowledge_items_default = defineTool4({
  name: "list_knowledge_items",
  title: "List knowledge sources",
  description: "List the user's knowledge base sources (videos, PDFs, links) and their extraction status.",
  inputSchema: {
    status: z4.string().optional().describe("Filter by status, e.g. pending, processing, ready, failed."),
    limit: z4.number().int().min(1).max(100).optional().describe("Max items to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("knowledge_base_items").select("id,title,type,status,url,brain_type,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error) throw new ToolError4(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-prospect-message.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var log_prospect_message_default = defineTool5({
  name: "log_prospect_message",
  title: "Log a prospect message",
  description: "Append a message to a prospect's thread (inbound from the prospect or outbound from the user).",
  inputSchema: {
    prospect_id: z5.string().describe("The prospect's id (from list_prospects)."),
    content: z5.string().describe("Message text to store."),
    direction: z5.enum(["inbound", "outbound"]).describe("inbound = from the prospect, outbound = sent by the user.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ prospect_id, content, direction }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const text = content.trim();
    if (!text) throw new ToolError5("content must not be empty");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("chat_messages").insert({ prospect_id, content: text, direction, user_id: ctx.getUserId(), is_ai_suggestion: false }).select("id,content,direction,created_at").maybeSingle();
    if (error) throw new ToolError5(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "iyqwrgqyfsfqgqqhlbec";
var mcp_default = defineMcp({
  name: "code-mirror-hub",
  title: "Legacy Sales Coach",
  version: "0.1.0",
  instructions: "Tools for the user's AI sales coach workspace. Use `list_prospects` to find prospects, `get_prospect_thread` to read a conversation, `search_sales_brain` to pull the user's own extracted sales principles before advising, `list_knowledge_items` to check knowledge sources and extraction status, and `log_prospect_message` to append a message to a thread. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_prospects_default, get_prospect_thread_default, search_sales_brain_default, list_knowledge_items_default, log_prospect_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
